print("preguntas filosoficas")
nombre = input("¿cual es tu nombre?")
print("estas preparado")
respuesta = input("¿Quieres responder a las preguntas filosoficas? (si/no)")
print("Muy bien, comencemos")
nombre = input("¿cual es el sentido de la vida?")
print("muy bien")
print("siguiente pregunta")
nombre = input("¿como se hacen los celulares?")
print("muy bien")
print("siguiente pregunta")
nombre = input("¿que es el amor?")
print("muy bien")
print("siguiente pregunta")
nombre = input("¿que es la felicidad?")
print("muy bien")
print("siguiente pregunta")
nombre = input("¿que es la realidad?")
print("muy bien")
print("siguiente pregunta")
nombre = input("¿que es la verdad?")
print("muy bien")
print("y terminamos")
print("gracias por jugar")
import time
import sys

print("Se cierra en 3 segundos...")

time.sleep(3)

sys.exit()